version: "3.4"

services:
  promtail:
    image: grafana/promtail:1.6.0
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      - ./promtail:/etc/promtail
      - /{log-directory}/log:/log/{job}
    network_mode: host
